"""Initial SQL Server baseline

Revision ID: dfc46693c03a
Revises: 
Create Date: 2026-04-15 22:53:14.724398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'dfc46693c03a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SavedAnalysisRuns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('IX_SavedAnalysisRuns_PortfolioId_CreatedAt'))
        batch_op.drop_index(batch_op.f('IX_SavedAnalysisRuns_UserId_CreatedAt'))

    op.drop_table('SavedAnalysisRuns')
    with op.batch_alter_table('FinancialSnapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('IX_FinancialSnapshots_Ticker_ReportDate'))

    op.drop_table('FinancialSnapshots')
    with op.batch_alter_table('Watchlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('IX_Watchlists_UserId'))

    op.drop_table('Watchlists')
    with op.batch_alter_table('NewsCache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('IX_NewsCache_PublishedAt'))
        batch_op.drop_index(batch_op.f('IX_NewsCache_Ticker_PublishedAt'))

    op.drop_table('NewsCache')
    with op.batch_alter_table('MarketPrices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('IX_MarketPrices_TradeDate'))

    op.drop_table('MarketPrices')
    with op.batch_alter_table('PortfolioHoldingsCache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('IX_PortfolioHoldingsCache_PortfolioId'))
        batch_op.drop_index(batch_op.f('IX_PortfolioHoldingsCache_Ticker'))

    op.drop_table('PortfolioHoldingsCache')
    with op.batch_alter_table('AiAdviceLogs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('IX_AiAdviceLogs_PortfolioId_CreatedAt'))
        batch_op.drop_index(batch_op.f('IX_AiAdviceLogs_UserId_CreatedAt'))

    op.drop_table('AiAdviceLogs')
    with op.batch_alter_table('WatchlistItems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('IX_WatchlistItems_Ticker'))

    op.drop_table('WatchlistItems')
    with op.batch_alter_table('AuditLogs', schema=None) as batch_op:
        batch_op.alter_column('CreatedAt',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))
        batch_op.drop_index(batch_op.f('IX_AuditLogs_CreatedAt'))
        batch_op.drop_index(batch_op.f('IX_AuditLogs_Entity'))
        batch_op.drop_index(batch_op.f('IX_AuditLogs_UserId'))
        batch_op.create_index(batch_op.f('ix_dbo_AuditLogs_Action'), ['Action'], unique=False)
        batch_op.create_index(batch_op.f('ix_dbo_AuditLogs_AuditLogId'), ['AuditLogId'], unique=False)
        batch_op.create_index(batch_op.f('ix_dbo_AuditLogs_UserId'), ['UserId'], unique=False)
        batch_op.drop_constraint(batch_op.f('FK_AuditLogs_Users'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['UserId'], ['UserId'], referent_schema='dbo')

    with op.batch_alter_table('ChatMessages', schema=None) as batch_op:
        batch_op.alter_column('CreatedAt',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))
        batch_op.drop_index(batch_op.f('IX_ChatMessages_ThreadId_CreatedAt'))
        batch_op.create_index(batch_op.f('ix_dbo_ChatMessages_MessageId'), ['MessageId'], unique=False)
        batch_op.create_index(batch_op.f('ix_dbo_ChatMessages_ThreadId'), ['ThreadId'], unique=False)
        batch_op.drop_constraint(batch_op.f('FK_ChatMessages_ChatThreads'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ChatThreads', ['ThreadId'], ['ThreadId'], referent_schema='dbo', ondelete='CASCADE')

    with op.batch_alter_table('ChatThreads', schema=None) as batch_op:
        batch_op.alter_column('CreatedAt',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))
        batch_op.alter_column('UpdatedAt',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))
        batch_op.drop_index(batch_op.f('IX_ChatThreads_PortfolioId'))
        batch_op.drop_index(batch_op.f('IX_ChatThreads_UserId'))
        batch_op.drop_index(batch_op.f('IX_ChatThreads_UserId_UpdatedAt'))
        batch_op.create_index(batch_op.f('ix_dbo_ChatThreads_ThreadId'), ['ThreadId'], unique=False)
        batch_op.create_index(batch_op.f('ix_dbo_ChatThreads_UserId'), ['UserId'], unique=False)
        batch_op.drop_constraint(batch_op.f('FK_ChatThreads_Users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('FK_ChatThreads_Portfolios'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['UserId'], ['UserId'], referent_schema='dbo')
        batch_op.create_foreign_key(None, 'Portfolios', ['PortfolioId'], ['PortfolioId'], referent_schema='dbo')

    with op.batch_alter_table('PortfolioSnapshots', schema=None) as batch_op:
        batch_op.alter_column('CreatedAt',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))
        batch_op.drop_index(batch_op.f('IX_PortfolioSnapshots_Portfolio_SnapshotDate'))
        batch_op.drop_index(batch_op.f('IX_PortfolioSnapshots_SnapshotDate'))
        batch_op.create_index(batch_op.f('ix_dbo_PortfolioSnapshots_PortfolioId'), ['PortfolioId'], unique=False)
        batch_op.create_index(batch_op.f('ix_dbo_PortfolioSnapshots_SnapshotDate'), ['SnapshotDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_dbo_PortfolioSnapshots_SnapshotId'), ['SnapshotId'], unique=False)
        batch_op.drop_constraint(batch_op.f('FK_PortfolioSnapshots_Portfolios'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Portfolios', ['PortfolioId'], ['PortfolioId'], referent_schema='dbo', ondelete='CASCADE')

    with op.batch_alter_table('Portfolios', schema=None) as batch_op:
        batch_op.alter_column('CreatedAt',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))
        batch_op.alter_column('UpdatedAt',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))
        batch_op.drop_index(batch_op.f('IX_Portfolios_UserId'))
        batch_op.drop_index(batch_op.f('IX_Portfolios_UserId_IsDefault'))
        batch_op.create_index(batch_op.f('ix_dbo_Portfolios_PortfolioId'), ['PortfolioId'], unique=False)
        batch_op.drop_constraint(batch_op.f('FK_Portfolios_Users'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['UserId'], ['UserId'], referent_schema='dbo', ondelete='CASCADE')

    with op.batch_alter_table('RefreshTokens', schema=None) as batch_op:
        batch_op.alter_column('ExpiresAt',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('RevokedAt',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('CreatedAt',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))
        batch_op.drop_index(batch_op.f('IX_RefreshTokens_ExpiresAt'))
        batch_op.drop_index(batch_op.f('IX_RefreshTokens_UserId'))
        batch_op.create_index(batch_op.f('ix_dbo_RefreshTokens_TokenHash'), ['TokenHash'], unique=True)
        batch_op.create_index(batch_op.f('ix_dbo_RefreshTokens_TokenId'), ['TokenId'], unique=False)
        batch_op.drop_constraint(batch_op.f('FK_RefreshTokens_Users'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['UserId'], ['UserId'], referent_schema='dbo', ondelete='CASCADE')

    with op.batch_alter_table('Reports', schema=None) as batch_op:
        batch_op.alter_column('CreatedAt',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))
        batch_op.drop_index(batch_op.f('IX_Reports_PortfolioId_CreatedAt'))
        batch_op.drop_index(batch_op.f('IX_Reports_UserId_CreatedAt'))
        batch_op.create_index(batch_op.f('ix_dbo_Reports_ReportId'), ['ReportId'], unique=False)
        batch_op.create_index(batch_op.f('ix_dbo_Reports_UserId'), ['UserId'], unique=False)
        batch_op.drop_constraint(batch_op.f('FK_Reports_Users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('FK_Reports_Portfolios'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Portfolios', ['PortfolioId'], ['PortfolioId'], referent_schema='dbo')
        batch_op.create_foreign_key(None, 'Users', ['UserId'], ['UserId'], referent_schema='dbo')

    with op.batch_alter_table('Stocks', schema=None) as batch_op:
        batch_op.alter_column('CreatedAt',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))
        batch_op.create_index(batch_op.f('ix_dbo_Stocks_Ticker'), ['Ticker'], unique=False)

    with op.batch_alter_table('Transactions', schema=None) as batch_op:
        batch_op.alter_column('CreatedAt',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))
        batch_op.alter_column('UpdatedAt',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))
        batch_op.drop_index(batch_op.f('IX_Transactions_Portfolio_Ticker_Date'))
        batch_op.drop_index(batch_op.f('IX_Transactions_Portfolio_TradeDate'))
        batch_op.drop_index(batch_op.f('IX_Transactions_Ticker_TradeDate'))
        batch_op.create_index(batch_op.f('ix_dbo_Transactions_PortfolioId'), ['PortfolioId'], unique=False)
        batch_op.create_index(batch_op.f('ix_dbo_Transactions_Ticker'), ['Ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_dbo_Transactions_TradeDate'), ['TradeDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_dbo_Transactions_TransactionId'), ['TransactionId'], unique=False)
        batch_op.drop_constraint(batch_op.f('FK_Transactions_Stocks'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('FK_Transactions_Portfolios'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Portfolios', ['PortfolioId'], ['PortfolioId'], referent_schema='dbo', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'Stocks', ['Ticker'], ['Ticker'], referent_schema='dbo')

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('CreatedAt',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))
        batch_op.alter_column('UpdatedAt',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))
        batch_op.create_index(batch_op.f('ix_dbo_Users_Email'), ['Email'], unique=True)
        batch_op.create_index(batch_op.f('ix_dbo_Users_FullName'), ['FullName'], unique=False)
        batch_op.create_index(batch_op.f('ix_dbo_Users_UserId'), ['UserId'], unique=False)
        batch_op.create_index(batch_op.f('ix_dbo_Users_Username'), ['Username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dbo_Users_Username'))
        batch_op.drop_index(batch_op.f('ix_dbo_Users_UserId'))
        batch_op.drop_index(batch_op.f('ix_dbo_Users_FullName'))
        batch_op.drop_index(batch_op.f('ix_dbo_Users_Email'))
        batch_op.alter_column('UpdatedAt',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))
        batch_op.alter_column('CreatedAt',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))

    with op.batch_alter_table('Transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('FK_Transactions_Portfolios'), 'Portfolios', ['PortfolioId'], ['PortfolioId'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('FK_Transactions_Stocks'), 'Stocks', ['Ticker'], ['Ticker'])
        batch_op.drop_index(batch_op.f('ix_dbo_Transactions_TransactionId'))
        batch_op.drop_index(batch_op.f('ix_dbo_Transactions_TradeDate'))
        batch_op.drop_index(batch_op.f('ix_dbo_Transactions_Ticker'))
        batch_op.drop_index(batch_op.f('ix_dbo_Transactions_PortfolioId'))
        batch_op.create_index(batch_op.f('IX_Transactions_Ticker_TradeDate'), ['Ticker', 'TradeDate'], unique=False)
        batch_op.create_index(batch_op.f('IX_Transactions_Portfolio_TradeDate'), ['PortfolioId', 'TradeDate'], unique=False)
        batch_op.create_index(batch_op.f('IX_Transactions_Portfolio_Ticker_Date'), ['PortfolioId', 'Ticker', 'TradeDate'], unique=False)
        batch_op.alter_column('UpdatedAt',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))
        batch_op.alter_column('CreatedAt',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))

    with op.batch_alter_table('Stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dbo_Stocks_Ticker'))
        batch_op.alter_column('CreatedAt',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))

    with op.batch_alter_table('Reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('FK_Reports_Portfolios'), 'Portfolios', ['PortfolioId'], ['PortfolioId'])
        batch_op.create_foreign_key(batch_op.f('FK_Reports_Users'), 'Users', ['UserId'], ['UserId'])
        batch_op.drop_index(batch_op.f('ix_dbo_Reports_UserId'))
        batch_op.drop_index(batch_op.f('ix_dbo_Reports_ReportId'))
        batch_op.create_index(batch_op.f('IX_Reports_UserId_CreatedAt'), ['UserId', 'CreatedAt'], unique=False)
        batch_op.create_index(batch_op.f('IX_Reports_PortfolioId_CreatedAt'), ['PortfolioId', 'CreatedAt'], unique=False)
        batch_op.alter_column('CreatedAt',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))

    with op.batch_alter_table('RefreshTokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('FK_RefreshTokens_Users'), 'Users', ['UserId'], ['UserId'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_dbo_RefreshTokens_TokenId'))
        batch_op.drop_index(batch_op.f('ix_dbo_RefreshTokens_TokenHash'))
        batch_op.create_index(batch_op.f('IX_RefreshTokens_UserId'), ['UserId'], unique=False)
        batch_op.create_index(batch_op.f('IX_RefreshTokens_ExpiresAt'), ['ExpiresAt'], unique=False)
        batch_op.alter_column('CreatedAt',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))
        batch_op.alter_column('RevokedAt',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True)
        batch_op.alter_column('ExpiresAt',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False)

    with op.batch_alter_table('Portfolios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('FK_Portfolios_Users'), 'Users', ['UserId'], ['UserId'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_dbo_Portfolios_PortfolioId'))
        batch_op.create_index(batch_op.f('IX_Portfolios_UserId_IsDefault'), ['UserId', 'IsDefault'], unique=False)
        batch_op.create_index(batch_op.f('IX_Portfolios_UserId'), ['UserId'], unique=False)
        batch_op.alter_column('UpdatedAt',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))
        batch_op.alter_column('CreatedAt',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))

    with op.batch_alter_table('PortfolioSnapshots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('FK_PortfolioSnapshots_Portfolios'), 'Portfolios', ['PortfolioId'], ['PortfolioId'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_dbo_PortfolioSnapshots_SnapshotId'))
        batch_op.drop_index(batch_op.f('ix_dbo_PortfolioSnapshots_SnapshotDate'))
        batch_op.drop_index(batch_op.f('ix_dbo_PortfolioSnapshots_PortfolioId'))
        batch_op.create_index(batch_op.f('IX_PortfolioSnapshots_SnapshotDate'), ['SnapshotDate'], unique=False)
        batch_op.create_index(batch_op.f('IX_PortfolioSnapshots_Portfolio_SnapshotDate'), ['PortfolioId', 'SnapshotDate'], unique=False)
        batch_op.alter_column('CreatedAt',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))

    with op.batch_alter_table('ChatThreads', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('FK_ChatThreads_Portfolios'), 'Portfolios', ['PortfolioId'], ['PortfolioId'])
        batch_op.create_foreign_key(batch_op.f('FK_ChatThreads_Users'), 'Users', ['UserId'], ['UserId'])
        batch_op.drop_index(batch_op.f('ix_dbo_ChatThreads_UserId'))
        batch_op.drop_index(batch_op.f('ix_dbo_ChatThreads_ThreadId'))
        batch_op.create_index(batch_op.f('IX_ChatThreads_UserId_UpdatedAt'), ['UserId', 'UpdatedAt'], unique=False)
        batch_op.create_index(batch_op.f('IX_ChatThreads_UserId'), ['UserId'], unique=False)
        batch_op.create_index(batch_op.f('IX_ChatThreads_PortfolioId'), ['PortfolioId'], unique=False)
        batch_op.alter_column('UpdatedAt',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))
        batch_op.alter_column('CreatedAt',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))

    with op.batch_alter_table('ChatMessages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('FK_ChatMessages_ChatThreads'), 'ChatThreads', ['ThreadId'], ['ThreadId'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_dbo_ChatMessages_ThreadId'))
        batch_op.drop_index(batch_op.f('ix_dbo_ChatMessages_MessageId'))
        batch_op.create_index(batch_op.f('IX_ChatMessages_ThreadId_CreatedAt'), ['ThreadId', 'CreatedAt'], unique=False)
        batch_op.alter_column('CreatedAt',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))

    with op.batch_alter_table('AuditLogs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('FK_AuditLogs_Users'), 'Users', ['UserId'], ['UserId'])
        batch_op.drop_index(batch_op.f('ix_dbo_AuditLogs_UserId'))
        batch_op.drop_index(batch_op.f('ix_dbo_AuditLogs_AuditLogId'))
        batch_op.drop_index(batch_op.f('ix_dbo_AuditLogs_Action'))
        batch_op.create_index(batch_op.f('IX_AuditLogs_UserId'), ['UserId'], unique=False)
        batch_op.create_index(batch_op.f('IX_AuditLogs_Entity'), ['EntityType', 'EntityId'], unique=False)
        batch_op.create_index(batch_op.f('IX_AuditLogs_CreatedAt'), ['CreatedAt'], unique=False)
        batch_op.alter_column('CreatedAt',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False,
               existing_server_default=sa.text('(sysutcdatetime())'))

    op.create_table('WatchlistItems',
    sa.Column('WatchlistItemId', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('WatchlistId', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('Ticker', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Note', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', mssql.DATETIME2(), server_default=sa.text('(sysutcdatetime())'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Ticker'], ['Stocks.Ticker'], name=op.f('FK_WatchlistItems_Stocks')),
    sa.ForeignKeyConstraint(['WatchlistId'], ['Watchlists.WatchlistId'], name=op.f('FK_WatchlistItems_Watchlists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('WatchlistItemId', name=op.f('PK_WatchlistItems'))
    )
    with op.batch_alter_table('WatchlistItems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IX_WatchlistItems_Ticker'), ['Ticker'], unique=False)

    op.create_table('AiAdviceLogs',
    sa.Column('AdviceLogId', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('UserId', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('PortfolioId', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ThreadId', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('PromptText', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('ResponseText', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ModelName', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', mssql.DATETIME2(), server_default=sa.text('(sysutcdatetime())'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['PortfolioId'], ['Portfolios.PortfolioId'], name=op.f('FK_AiAdviceLogs_Portfolios')),
    sa.ForeignKeyConstraint(['ThreadId'], ['ChatThreads.ThreadId'], name=op.f('FK_AiAdviceLogs_ChatThreads')),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], name=op.f('FK_AiAdviceLogs_Users')),
    sa.PrimaryKeyConstraint('AdviceLogId', name=op.f('PK_AiAdviceLogs'))
    )
    with op.batch_alter_table('AiAdviceLogs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IX_AiAdviceLogs_UserId_CreatedAt'), ['UserId', 'CreatedAt'], unique=False)
        batch_op.create_index(batch_op.f('IX_AiAdviceLogs_PortfolioId_CreatedAt'), ['PortfolioId', 'CreatedAt'], unique=False)

    op.create_table('PortfolioHoldingsCache',
    sa.Column('HoldingCacheId', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('PortfolioId', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('Ticker', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Quantity', sa.DECIMAL(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('AvgPrice', sa.DECIMAL(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('CostBasis', sa.DECIMAL(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('MarketPrice', sa.DECIMAL(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('MarketValue', sa.DECIMAL(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('UnrealizedPnl', sa.DECIMAL(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('Weight', sa.DECIMAL(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('LastRebuiltAt', mssql.DATETIME2(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['PortfolioId'], ['Portfolios.PortfolioId'], name=op.f('FK_PortfolioHoldingsCache_Portfolios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Ticker'], ['Stocks.Ticker'], name=op.f('FK_PortfolioHoldingsCache_Stocks')),
    sa.PrimaryKeyConstraint('HoldingCacheId', name=op.f('PK_PortfolioHoldingsCache'))
    )
    with op.batch_alter_table('PortfolioHoldingsCache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IX_PortfolioHoldingsCache_Ticker'), ['Ticker'], unique=False)
        batch_op.create_index(batch_op.f('IX_PortfolioHoldingsCache_PortfolioId'), ['PortfolioId'], unique=False)

    op.create_table('MarketPrices',
    sa.Column('PriceId', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Ticker', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('TradeDate', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('OpenPrice', sa.DECIMAL(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('HighPrice', sa.DECIMAL(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('LowPrice', sa.DECIMAL(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('ClosePrice', sa.DECIMAL(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('Volume', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', mssql.DATETIME2(), server_default=sa.text('(sysutcdatetime())'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Ticker'], ['Stocks.Ticker'], name=op.f('FK_MarketPrices_Stocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('PriceId', name=op.f('PK_MarketPrices'))
    )
    with op.batch_alter_table('MarketPrices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IX_MarketPrices_TradeDate'), ['TradeDate'], unique=False)

    op.create_table('NewsCache',
    sa.Column('NewsId', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Ticker', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Title', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Source', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('PublishedAt', mssql.DATETIME2(), autoincrement=False, nullable=True),
    sa.Column('Sentiment', sa.DECIMAL(precision=8, scale=4), autoincrement=False, nullable=True),
    sa.Column('Summary', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Url', sa.VARCHAR(length=500, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', mssql.DATETIME2(), server_default=sa.text('(sysutcdatetime())'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Ticker'], ['Stocks.Ticker'], name=op.f('FK_NewsCache_Stocks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('NewsId', name=op.f('PK_NewsCache'))
    )
    with op.batch_alter_table('NewsCache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IX_NewsCache_Ticker_PublishedAt'), ['Ticker', 'PublishedAt'], unique=False)
        batch_op.create_index(batch_op.f('IX_NewsCache_PublishedAt'), ['PublishedAt'], unique=False)

    op.create_table('Watchlists',
    sa.Column('WatchlistId', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('UserId', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('CreatedAt', mssql.DATETIME2(), server_default=sa.text('(sysutcdatetime())'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], name=op.f('FK_Watchlists_Users')),
    sa.PrimaryKeyConstraint('WatchlistId', name=op.f('PK_Watchlists'))
    )
    with op.batch_alter_table('Watchlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IX_Watchlists_UserId'), ['UserId'], unique=False)

    op.create_table('FinancialSnapshots',
    sa.Column('FinancialSnapshotId', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Ticker', sa.VARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('ReportDate', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('Revenue', sa.DECIMAL(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('Profit', sa.DECIMAL(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('Eps', sa.DECIMAL(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('PayloadJson', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', mssql.DATETIME2(), server_default=sa.text('(sysutcdatetime())'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Ticker'], ['Stocks.Ticker'], name=op.f('FK_FinancialSnapshots_Stocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('FinancialSnapshotId', name=op.f('PK_FinancialSnapshots'))
    )
    with op.batch_alter_table('FinancialSnapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IX_FinancialSnapshots_Ticker_ReportDate'), ['Ticker', 'ReportDate'], unique=False)

    op.create_table('SavedAnalysisRuns',
    sa.Column('RunId', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('PortfolioId', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('UserId', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('RunType', sa.VARCHAR(length=30, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('InputJson', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ResultJson', sa.NVARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('SummaryText', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', mssql.DATETIME2(), server_default=sa.text('(sysutcdatetime())'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['PortfolioId'], ['Portfolios.PortfolioId'], name=op.f('FK_SavedAnalysisRuns_Portfolios')),
    sa.ForeignKeyConstraint(['UserId'], ['Users.UserId'], name=op.f('FK_SavedAnalysisRuns_Users')),
    sa.PrimaryKeyConstraint('RunId', name=op.f('PK_SavedAnalysisRuns'))
    )
    with op.batch_alter_table('SavedAnalysisRuns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IX_SavedAnalysisRuns_UserId_CreatedAt'), ['UserId', 'CreatedAt'], unique=False)
        batch_op.create_index(batch_op.f('IX_SavedAnalysisRuns_PortfolioId_CreatedAt'), ['PortfolioId', 'CreatedAt'], unique=False)

    # ### end Alembic commands ###
